steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'europe-west1-docker.pkg.dev/bmi-final-proje/bmi-repo/bmi-app:$COMMIT_SHA', '-t', 'europe-west1-docker.pkg.dev/bmi-final-proje/bmi-repo/bmi-app:latest', '.']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'europe-west1-docker.pkg.dev/bmi-final-proje/bmi-repo/bmi-app:$COMMIT_SHA']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'europe-west1-docker.pkg.dev/bmi-final-proje/bmi-repo/bmi-app:latest']

  - name: 'gcr.io/cloud-builders/gcloud'
    args:
    - 'container'
    - 'clusters'
    - 'get-credentials'
    - 'bmi-cluster'
    - '--zone'
    - 'europe-west1-b'
    - '--project'
    - 'bmi-final-proje'

  - name: 'gcr.io/cloud-builders/kubectl'
    args: ['set', 'image', 'deployment/bmi-deployment', 'bmi-app=europe-west1-docker.pkg.dev/bmi-final-proje/bmi-repo/bmi-app:$COMMIT_SHA', '-n', 'bmi-app']
    env:
    - 'CLOUDSDK_COMPUTE_ZONE=europe-west1-b'
    - 'CLOUDSDK_CONTAINER_CLUSTER=bmi-cluster'

  - name: 'gcr.io/cloud-builders/kubectl'
    args: ['rollout', 'status', 'deployment/bmi-deployment', '-n', 'bmi-app', '--timeout=5m']
    env:
    - 'CLOUDSDK_COMPUTE_ZONE=europe-west1-b'
    - 'CLOUDSDK_CONTAINER_CLUSTER=bmi-cluster'

options:
  logging: CLOUD_LOGGING_ONLY

images:
  - 'europe-west1-docker.pkg.dev/bmi-final-proje/bmi-repo/bmi-app:$COMMIT_SHA'
  - 'europe-west1-docker.pkg.dev/bmi-final-proje/bmi-repo/bmi-app:latest'
